### ISSUE TITLE
Configure Grid Lines on Column Chart

### ISSUE THREAD

**Issue by rheubach** [unchartedelixir/uncharted#6]
The grid lines are located in a nested SVG with class="columns__graph". We need the following configurations for the graph lines:

- **Display**, which can be set to true or false. False would remove the whole nested SVG. 
- **Line Color**, which can be can be assigned a color or gradient. All line elements in the nested SVG should have the stroke attribute set to defined color.
- **Line Width**, which can be can be assigned an integer. All line elements in the nested SVG should have the stroke-width attribute set to the defined integer.

**Comment by alcwhite** [comment]
Should the display configuration use the show_gridlines field on xy_axes/base_axes, or a separate field on the magnitude axis?

**Comment by rheubach** [comment]
Sorry @alcwhite, some of the confusion was from the fact that I changed the class names and forgot to update this issue. The div with the class name "chart-lines" included all the grid lines which also included the base x and y lines. A show_gridlines field would show or hide all of them but not affect the labels.

**Comment by alcwhite** [comment]
So would this then not hide the base x and y lines?
